---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Define Python packages
  ansible.builtin.set_fact:
    peering_manager_python_packages: "{{ __peering_manager_python_packages | list }}"
  when: peering_manager_python_packages is not defined

- name: Define PostgreSQL packages
  ansible.builtin.set_fact:
    peering_manager_postgresql_packages: "{{ __peering_manager_postgresql_packages | list }}"
  when: peering_manager_postgresql_packages is not defined

- name: Define Redis packages
  ansible.builtin.set_fact:
    peering_manager_redis_packages: "{{ __peering_manager_redis_packages | list }}"
  when: peering_manager_redis_packages is not defined

- name: Define LDAP packages
  ansible.builtin.set_fact:
    peering_manager_ldap_packages: "{{ __peering_manager_ldap_packages | list }}"
  when: peering_manager_ldap_packages is not defined

- name: Define other packages
  ansible.builtin.set_fact:
    peering_manager_other_packages: "{{ __peering_manager_other_packages | list }}"
  when: peering_manager_other_packages is not defined

- name: Define web frontend packages
  ansible.builtin.set_fact:
    peering_manager_web_frontend_packages: "{{ __peering_manager_web_frontend_packages | list }}"
  when: peering_manager_web_frontend_packages is not defined
