---
- name: install required packages
  ansible.builtin.package:
    name: "{{ __peering_manager_required_packages | flatten }}"
    state: present
  become: true
  vars:
    __peering_manager_required_packages:
      - "{{ peering_manager_python_packages }}"
      - "{{ peering_manager_postgresql_packages }}"
      - "{{ peering_manager_redis_packages }}"
      - "{{ peering_manager_ldap_packages }}"
      - "{{ peering_manager_other_packages }}"
      - "{{ peering_manager_web_frontend_packages if peering_manager_setup_web_frontend else [] }}"
  register: package_result
  until: package_result is success
