---
- name: Converge
  hosts: all

  vars:
    peering_manager_setup_ldap_auth: true
    peering_manager_setup_systemd: true
    peering_manager_setup_web_frontend: true

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: gmazoyer.peering_manager
